"""Write the manifest, the readable inventory and the attribution file."""

import json

import config

SUMMARY_KEYS = (
    "format",
    "codec",
    "width",
    "height",
    "frames",
    "video_codec",
    "audio_codec",
    "sample_rate",
    "channels",
    "duration_s",
    "audio_tracks",
    "subtitle_tracks",
    "cover_art",
    "lines",
)
SOURCE_DESCRIPTION_MAX = 280


def summarise(properties):
    """Return a compact `key=value` summary of measured properties."""
    assert properties, "summarise: empty properties"
    parts = [
        f"{key}={properties[key]}" for key in SUMMARY_KEYS if key in properties
    ]
    return ", ".join(parts)


def shorten(text, width):
    """Truncate text on a word boundary with an ellipsis."""
    assert width > 4, "shorten: width"
    if len(text) <= width:
        return text
    cut = text[: width - 1].rsplit(" ", 1)[0]
    return cut + "…"


def write_manifest(records):
    """Write manifest.json and return it."""
    assert records, "write_manifest: no records"
    manifest = {
        "schema": config.SCHEMA_VERSION,
        "pkgver": config.PKGVER,
        "generated_by": "tools/generate.py",
        "count": len(records),
        "total_bytes": sum(item["bytes"] for item in records),
        "fixtures": records,
    }
    config.MANIFEST_PATH.write_text(
        json.dumps(manifest, indent=2, sort_keys=True, ensure_ascii=False)
        + "\n",
        encoding="utf-8",
    )
    assert config.MANIFEST_PATH.stat().st_size > 0, "write_manifest: empty file"
    return manifest


def load_manifest():
    """Read manifest.json."""
    with config.MANIFEST_PATH.open(encoding="utf-8") as handle:
        manifest = json.load(handle)
    assert manifest["fixtures"], "load_manifest: no fixtures"
    return manifest


def write_checksums(records):
    """Write a `sha256sum -c` compatible list."""
    lines = [f"{item['sha256']}  {item['path']}\n" for item in records]
    config.CHECKSUMS_PATH.write_text("".join(lines), encoding="utf-8")
    assert config.CHECKSUMS_PATH.stat().st_size > 0, "write_checksums: empty"
    return config.CHECKSUMS_PATH


def write_expected(records):
    """Write EXPECTED.md: the human-readable inventory."""
    total_kib = sum(item["bytes"] for item in records) / 1024
    lines = [
        "# Expected fixture inventory",
        "",
        "Generated by `tools/generate.py`. Every value below was measured from",
        "the file that ships, not assumed. `tools/generate.py --verify` fails",
        "when a file stops matching its row.",
        "",
        f"Fixtures: {len(records)}. Total size: {total_kib:.1f} KiB.",
        "",
        "| Fixture | Kind | Description | Measured | Bytes |",
        "| --- | --- | --- | --- | --- |",
    ]
    for item in sorted(records, key=lambda entry: entry["path"]):
        description = item["description"].replace("|", "\\|")
        summary = summarise(item["properties"])
        lines.append(
            f"| `{item['path']}` | {item['kind']} | {description} | "
            f"{summary} | {item['bytes']} |"
        )
    lines.append("")
    config.EXPECTED_PATH.write_text("\n".join(lines), encoding="utf-8")
    assert config.EXPECTED_PATH.stat().st_size > 0, "write_expected: empty"
    return config.EXPECTED_PATH


def write_attribution(records):
    """Write ATTRIBUTION.md: what each downloaded file shows and who made it."""
    downloads = [item for item in records if item.get("source")]
    lines = [
        "# Attribution",
        "",
        "Files generated by the scripts in `tools/` are released under",
        "CC0-1.0 (see `LICENSE`).",
        "",
        "The files below are derived from public domain material on Wikimedia",
        "Commons. Attribution is not required for public domain works; it is",
        "recorded anyway, together with the changes made to each original.",
        "",
        f"Downloaded sources: {len(downloads)} fixtures from "
        f"{len({item['source']['title'] for item in downloads})} files.",
        "",
    ]
    for item in sorted(downloads, key=lambda entry: entry["path"]):
        source = item["source"]
        lines.extend(
            [
                f"## `{item['path']}`",
                "",
                f"- Shows: {item['description']}",
                f"- Original: {source['title']}",
                f"- Original description: "
                f"{shorten(source['description'], SOURCE_DESCRIPTION_MAX)}",
                f"- Author: {source['author'] or 'not stated on Commons'}",
                f"- Source page: {source['url']}",
                f"- License: {source['license']}",
                f"- Changes: {source['changes']}",
                "",
            ]
        )
    config.ATTRIBUTION_PATH.write_text("\n".join(lines), encoding="utf-8")
    assert config.ATTRIBUTION_PATH.stat().st_size > 0, (
        "write_attribution: empty"
    )
    return config.ATTRIBUTION_PATH


def write_transcripts(records):
    """Write TRANSCRIPTS.md: the exact words each fixture carries."""
    spoken = [item for item in records if item.get("transcript")]
    lines = [
        "# What the fixtures say",
        "",
        "Words contained in the fixtures that carry text or speech. Generated",
        "files say what the builder renders or synthesizes. Downloaded",
        "recordings are transcribed on the source page, which is cited.",
        "",
        f"Fixtures with words: {len(spoken)}.",
        "",
    ]
    for item in sorted(spoken, key=lambda entry: entry["path"]):
        lines.extend([f"## `{item['path']}`", "", item["description"], ""])
        for line in item["transcript"].splitlines():
            lines.append(f"> {line}")
        lines.append("")
        if item.get("source"):
            lines.extend([f"Source page: {item['source']['url']}", ""])
    config.TRANSCRIPTS_PATH.write_text("\n".join(lines), encoding="utf-8")
    assert config.TRANSCRIPTS_PATH.stat().st_size > 0, (
        "write_transcripts: empty"
    )
    return config.TRANSCRIPTS_PATH


def write_all(records):
    """Write every report file."""
    assert len(records) > 0, "write_all: no records"
    write_manifest(records)
    write_checksums(records)
    write_expected(records)
    write_attribution(records)
    write_transcripts(records)
    return [
        config.MANIFEST_PATH,
        config.CHECKSUMS_PATH,
        config.EXPECTED_PATH,
        config.ATTRIBUTION_PATH,
        config.TRANSCRIPTS_PATH,
    ]
